version: "3.7"

services:
  postgres:
    image: postgres:alpine3.19
    container_name: postgres
    restart: always
    volumes:
      - db:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=api-trilha-devops
      - POSTGRES_USER=admin
    networks:
      - primeira-network
    deploy:
      resources:
        limits:
          cpus: "0.2"
          memory: 200M

  backend_1:
    build:
      context: .
    container_name: backend-1
    restart: always
    ports:
      - "8080"
    environment:
      - APP_PORT=8080
    depends_on:
      - postgres
    networks:
      - primeira-network
    deploy:
      resources:
        limits:
          cpus: "0.2"
          memory: 200M
  
  backend_2:
    build:
      context: .
    container_name: backend-2
    restart: always
    ports:
      - "8081"
    environment:
      - APP_PORT=8081
    depends_on:
      - postgres
    networks:
      - primeira-network
    deploy:
      resources:
        limits:
          cpus: "0.2"
          memory: 200M

  backend_3:
    build:
      context: .
    container_name: backend-3
    restart: always
    ports:
      - "8082"
    environment:
      - APP_PORT=8082
    depends_on:
      - postgres
    networks:
      - primeira-network
    deploy:
      resources:
        limits:
          cpus: "0.2"
          memory: 200M
  
  loadbalancer:
    build:
      context: ./nginx
    container_name: nginx
    restart: always
    networks:
      - primeira-network
    ports:
      - 3000:3000
    depends_on:
      - backend_1
      - backend_2
      - backend_3
    deploy:
      resources:
        limits:
          cpus: "0.2"
          memory: 200M

networks:
  primeira-network:
    name: primeira-network
    driver: bridge

volumes:
  db: